version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: alina
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      -

  bot:
    image: dockerbot:latest
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "5000:5000"
